ALTER TABLE public.settings
ADD COLUMN IF NOT EXISTS farm_types JSONB NOT NULL DEFAULT '["Mango Farm", "Rice Farm", "Coconut Farm", "Dairy Farm"]'::jsonb,
ADD COLUMN IF NOT EXISTS shop_cta_text TEXT NOT NULL DEFAULT 'Shop Mangoes';

ALTER TABLE public.farms
ADD COLUMN IF NOT EXISTS farm_type TEXT,
ADD COLUMN IF NOT EXISTS district TEXT,
ADD COLUMN IF NOT EXISTS mandal TEXT,
ADD COLUMN IF NOT EXISTS village TEXT,
ADD COLUMN IF NOT EXISTS pincode TEXT;

ALTER TABLE public.applications
ADD COLUMN IF NOT EXISTS farm_type TEXT,
ADD COLUMN IF NOT EXISTS district TEXT,
ADD COLUMN IF NOT EXISTS mandal TEXT,
ADD COLUMN IF NOT EXISTS village TEXT,
ADD COLUMN IF NOT EXISTS pincode TEXT;
